- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: ping
      shell: ping -c3 google.com
      ignore_errors: false