- name: RHEL Perform STIG Check Script
  hosts: all
  tasks:
    - name: STIG Message
      debug:
        msg: "Performing STIG Checks on this system, please wait and review the below messages."
    
    - name: Perform STIG CAT I FIPS Mode If Enabled
      shell: sudo fips-mode-setup --check
      ignore_errors: false
      register: fips
    
    - debug: var=fips.stdout_lines
    
    - name: Perform STIG CAT I OS Version Support
      shell: sudo cat /etc/redhat-release
      ignore_errors: false
      register: rhel-release
      
    - debug: var=rhel-release.stdout_lines