- name: RHEL Update Security Script
  hosts: all
  tasks:
    - name: Update Message
      debug:
        msg: "Updating the Red Hat Server to the latest patches and security updates!"
    - name: Update the Server
      shell: sudo yum update -y
      ignore_errors: true
    - debug: var=out.stdout_lines