---
- name: Hello World First Ansible RHEL Playbook
  hosts: localhost
  tasks: 
  - name: Ping Hosts in AWS
    ansible.builtin.ping:
  - name: Print Message to Console
    ansible.builtin.debut: 
        msg: Hello World