- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true