- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: ping
      shell: ping -c 1 -w 2 www.youtube.com
      ignore_errors: false